
CREATE TABLE G_GROUPFRONTMENUS(
  NID Integer NOT NULL,
  CGROUP Varchar(50) NOT NULL,
  NURUT Integer NOT NULL,
  BHIDE Integer NOT NULL,
  CONSTRAINT PK_GROUPFRONTMENUS PRIMARY KEY (NID)
);

CREATE GENERATOR G_GROUPFRONTMENUS_NID;

SET    TERM !! ;
CREATE TRIGGER G_GROUPFRONTMENUS_BI FOR G_GROUPFRONTMENUS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.NID IS NULL) THEN
    NEW.NID = GEN_ID(G_GROUPFRONTMENUS_NID, 1);
END!!
SET TERM ; !!



CREATE TABLE G_FRONTMENUS(
  NID Integer NOT NULL,
  NID_GROUPFRONTMENUS Integer NOT NULL,
  CMENU Varchar(50) NOT NULL,
  CFUNCTION Varchar(50) NOT NULL,
  CPARAM Varchar(100) NOT NULL,
  NURUT Integer NOT NULL,
  BHIDE Integer DEFAULT 0 NOT NULL,
  BSECURE Integer DEFAULT 1 NOT NULL,
  CONSTRAINT PK_FRONTMENUS PRIMARY KEY (NID)
);
ALTER TABLE G_FRONTMENUS ADD CONSTRAINT FK_FRONTMENUS_GROUP
  FOREIGN KEY (NID_GROUPFRONTMENUS) REFERENCES G_GROUPFRONTMENUS (NID);

CREATE GENERATOR G_FRONTMENUS_NID;

SET TERM ^;
CREATE TRIGGER G_FRONTMENUS_BI FOR G_FRONTMENUS ACTIVE
BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.NID IS NULL) THEN
    NEW.NID = GEN_ID(G_FRONTMENUS_NID, 1);
END^
SET TERM ;^

ALTER TABLE G_FRONTMENUS ADD WIDTH INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE G_FRONTMENUS ADD HEIGHT INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE G_FRONTMENUS ADD IS_MAIN INTEGER DEFAULT 0 NOT NULL;

CREATE TABLE G_GRANTEDFRONTMENUS(
  NID Integer NOT NULL,
  NID_USERS Integer NOT NULL,
  NID_FRONTMENUS Integer NOT NULL,
  NSTATUS Integer NOT NULL,
  CONSTRAINT PK_GRANTEDFRONTMENUS PRIMARY KEY (NID)
);
ALTER TABLE G_GRANTEDFRONTMENUS ADD CONSTRAINT FK_GRANTEDFRONTMENUS_FRONTMENUS
  FOREIGN KEY (NID_FRONTMENUS) REFERENCES G_FRONTMENUS (NID);
ALTER TABLE G_GRANTEDFRONTMENUS ADD CONSTRAINT FK_GRANTEDFRONTMENUS_USERS
  FOREIGN KEY (NID_USERS) REFERENCES G_USERS (NID);

CREATE GENERATOR G_GRANTEDFRONTMENUS_NID;

SET TERM !! ;
CREATE TRIGGER G_GRANTEDFRONTMENUS_BI FOR G_GRANTEDFRONTMENUS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.NID IS NULL) THEN
    NEW.NID = GEN_ID(G_GRANTEDFRONTMENUS_NID, 1);
END!!
SET TERM ; !!




