//TABEL PEMDA
CREATE TABLE PEMDA(
  PEMDA_ID Integer NOT NULL,
  PEMDA_NAMA Varchar(100),
  PEMDA_LOKASI Varchar(100),
  PEMDA_LOGO_PATH Varchar(100),
  PEMDA_KODE Varchar(2),
  PEMDA_DATI Varchar(15),
  PEMDA_IBUKOTA Varchar(30),
  PEMDA_TELP Varchar(20),
  PEMDA_PEJABAT Varchar(50),
  PEMDA_BANK Varchar(100),
  PEMDA_BANK_NOREK Varchar(100),
  CONSTRAINT PK_PEMDA_1 PRIMARY KEY (PEMDA_ID)
);
CREATE UNIQUE INDEX IDX_PEMDA1 ON PEMDA (PEMDA_ID);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON PEMDA TO  SYSDBA WITH GRANT OPTION;

CREATE GENERATOR G_PEMDA_ID
SET GENERATOR G_PEMDA_ID TO 0;

SET TERM !! ;
CREATE TRIGGER PEMDA_BI FOR PEMDA
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.PEMDA_ID IS NULL) THEN
    NEW.PEMDA_ID = GEN_ID(, 1);
END!!
SET TERM ; !!
